apiVersion: apps/v1 #  Configurações do deployment
kind: Deployment
metadata:
  name: hi-nginx

spec:  #  Refere-se ao Deployment
  replicas: 2

  selector:  #  Utilizado para criação do service
    matchLabels:
      app: hi-nginx
  template:  #  Refernte ao POD
    metadata:
      labels:
        app: hi-nginx
            
    spec:  #  Spec do Pod
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "500m"
          limits:
            cpu: "250m"
              

        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true

      volumes:
      - name: nginx-conf  # Nome do arquico ConfigMap
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf   