apiVersion: apps/v1beta1 #  Configurações do deployment
kind: Deployment
metadata:
  name: hi-nginx

spec:  # Spec do Template do POD
  replicas: 2
  template:
    metadata:
      labels:
        app: hi-nginx
    spec:  #  Spec do Pod
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true

      volumes:
      - name: nginx-conf  # Nome do arquico ConfigMap
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf   