apiVersion: v1 
kind: Pod
metadata:
  name: kub-nginx
spec:
  containers:
  - name: pod-test
    image: nginx:1.17-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
