apiVersion: v1 
kind: Pod
metadata:
  name: test-nginx
spec:
  containers:
  - name: pod-test
    image: rof1966/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8085
