apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  
spec:  #  Refere-se ao Deployment
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: db

  template:  #  Refernte ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db

    spec:  #  Spec do POD
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"

        env:
        - name: MYSQL_ROOT_PASSWORD
        #  value: root
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
              
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

        ports:
        - containerPort: 3306
        volumeMounts:  #  Monta o volume efetivamente
        - name: mysql-presistent-storage
          mountPath: /var/lib/mysql

      volumes:
        - name: mysql-presistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim



